dist: trusty

env:
    global:
        - JEDISJEUX_CACHE_DIR=$HOME/.jedisjeux-cache
        - JEDISJEUX_BUILD_DIR=etc/build

matrix:
    include:
        -
            sudo: false
            php: 7.1
            env: JEDISJEUX_SUITE="docs packages"
            addons:
                apt:
                    packages:
                        - parallel
        -
            language: android
            sudo: required
            jdk: oraclejdk8
            cache:
                directories:
                    - $HOME/.yarn-cache
                    - $HOME/.gradle/caches/
                    - $HOME/.gradle/wrapper/
            android:
                components:
                  - build-tools-23.0.1
                  - android-23
                  - extra-android-m2repository
                  - extra-google-google_play_services
                  - extra-google-m2repository
                  - addon-google_apis-google-16
            env: JEDISJEUX_SUITE="android"

script: .travis/run.sh

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - ~/.cache/pip
        - node_modules
        - $JEDISJEUX_CACHE_DIR

before_install:
    - etc/travis/run-suite before_install "${JEDISJEUX_SUITE}"

install:
    - etc/travis/run-suite install "${JEDISJEUX_SUITE}"

before_script:
    - etc/travis/run-suite before_script "${JEDISJEUX_SUITE}"

script:
    - etc/travis/run-suite script "${JEDISJEUX_SUITE}"

before_cache:
    - etc/travis/run-suite before_cache "${JEDISJEUX_SUITE}"

after_success:
    - etc/travis/run-suite after_success "${JEDISJEUX_SUITE}"

after_failure:
    - etc/travis/run-suite after_failure "${JEDISJEUX_SUITE}"

after_script:
    - etc/travis/run-suite after_script "${JEDISJEUX_SUITE}"

notifications:
    email: false
